### ISSUE TITLE
uncaught error during startup (and when attempting to fetch data)

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [YukiGasai/obsidian-google-calendar#32]
Obsidian version: 1.0.3
Plugin version: 1.7.1
OS: Windows 11 22621.819

I followed the instructions in the README, but after startup am seeing this error

```

Uncaught (in promise) Error: Request failed, status 403
    at new t (app.js:1:699319)
    at Xb (app.js:1:699511)
    at app.js:1:700188
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
t	@	app.js:1
Xb	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
a	@	app.js:1
Promise.then (async)		
l	@	plugin:google-calendar:6
eval	@	plugin:google-calendar:6
U	@	plugin:google-calendar:6
eval	@	plugin:google-calendar:75
e.addDropdown	@	app.js:1
display	@	plugin:google-calendar:75
t.openTab	@	app.js:1
(anonymous)	@	app.js:1
```

I'm able to open webview, but the other commands seem to fail.

**Comment by CovetingEpiphany2152** [comment]
resolved! sorry about the false alarm.

it turns out that I enabled Google Calendar API for the wrong project! How silly!
